# Generated by Django 3.2.4 on 2021-07-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('url', models.TextField()),
                ('background', models.ImageField(upload_to='')),
            ],
        ),
    ]
