# Generated by Django 3.2.4 on 2021-07-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('job', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('instagram', models.TextField()),
                ('telegram', models.TextField()),
                ('facebook', models.TextField()),
            ],
        ),
    ]
