# Generated by Django 3.2.4 on 2021-07-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='feature_body',
        ),
        migrations.RemoveField(
            model_name='about',
            name='feature_icon',
        ),
        migrations.RemoveField(
            model_name='about',
            name='feature_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='feature_url',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service_icon',
        ),
    ]
