# Generated by Django 3.2.4 on 2021-07-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210727_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
